package by.training.task03.controller.command;

public enum CommandName {
    ARR_BUBBLE_SORT_INCREASE, ARR_BUBBLE_SORT_DECREASE, ARR_HASHING_SORT_INCREASE,
    ARR_HASHING_SORT_DECREASE,ARR_INSERTION_SORT_INCREASE, ARR_INSERTION_SORT_DECREASE,
    ARR_MERGE_SORT_INCREASE, ARR_MERGE_SORT_DECREASE, ARR_SHAKER_SORT_INCREASE,
    ARR_SHAKER_SORT_DECREASE, ARR_SHELL_SORT_INCREASE, ARR_SHELL_SORT_DECREASE,
    ARR_SIMPLE_CHOICE_SORT_INCREASE, ARR_SIMPLE_CHOICE_SORT_DECREASE, MATR_SUM,
    MATR_SUB, MATR_TRANSPOSE, MATR_POW, MATR_MULTIPLY_MATRIX, MATR_MULTIPLY_NUMBER,
    WRONG_REQUEST
}