package by.training.project.controller.command;

public enum CommandName {
    MAIN,SHOW_SIGN_IN,SHOW_ERROR_PAGE,
    SHOW_SIGN_UP,LOG_IN,SIGN_UP,ERROR_404,
    SHOW_CONTINUE_SIGN_UP,SHOW_CHECK_MAIL_PAGE,
    CONTINUE_SIGN_UP,LOG_OUT,SHOW_EDIT, EDIT_INFO,
    EDIT_PASSWORD, SHOW_SUCCESS_PASSWORD_PAGE,
    SHOW_EDIT_PASSWORD,SHOW_BOOKING, CONTINUE_BOOKING
}
